#!/bin/sh

image() {
	if [ -n "$DISPLAY" ] && [ -z "$WAYLAND_DISPLAY" ]; then
		printf '{"action": "add", "identifier": "PREVIEW", "x": "%s", "y": "%s", "width": "%s", "height": "%s", "scaler": "contain", "path": "%s"}\n' "$4" "$5" "$(($2-1))" "$(($3-1))" "$1" > "$FIFO_UEBERZUG"
		exit 1
	else
		chafa "$1" -s "$4x"
	fi
}

batorcat() {
	file="$1"
	shift
	if command -v bat > /dev/null 2>&1
	then
		bat --color=always --style=plain --pager=never "$file" "$@"
	else
		cat "$file"
	fi
}

glowormdcat() {
	file="$1"
	shift
	if command -v glow > /dev/null 2>&1
	then
		glow "$file"
	else
		mdcat "$file"
	fi
}

CACHE="$HOME/.cache/lf/thumbnail.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | awk '{print $1}'))"

case "$(printf "%s\n" "$(readlink -f "$1")" | awk '{print tolower($0)}')" in
	*.jpg|*.jpeg|*.png|*.webp|*.gif) image "$1" "$2" "$3" "$4" "$5" ;;
	*.md) glow "$1" ;;
	# *.doc|*.docx) pandoc -f docx -t pdf | pdftoppm -jpeg -singlefile -

	*) done ;;
	# *) case "$(file --dereference --brief --mime-type -- "$1")" in
			# image/*) image "$1" "$2" "$3" "$4" "$5" "$1" ;;
			# text/html)
		# esac ;;
esac
exit 1
