#!/bin/sh

battery=$(acpi | sed -n 2p | awk -F", " '{ print $2 }' | tr -d '%')
charging=$(acpi | sed -n 2p | awk -F", " '{ print $1 }' | awk -F": " '{ print $2 }')

if [ "$charging" = "Discharging" ] && [ "$battery" -le 25 ]; then
    echo " $battery%"
elif [ "$charging" = "Discharging" ] && [ "$battery" -le 60 ]; then
    echo " $battery%"
elif [ "$charging" = "Discharging" ] && [ "$battery" -le 100 ]; then
    echo " $battery%"
elif [ "$charging" = "Charging" ] && [ "$battery" -le 25 ]; then
    echo " $battery%"
elif [ "$charging" = "Charging" ] && [ "$battery" -le 60 ]; then
    echo " $battery%"
elif [ "$charging" = "Charging" ] && [ "$battery" -le 100 ]; then
    echo " $battery%"
elif [ "$charging" = 'Unknown' ]; then
    echo " $battery%"
fi
