#!/bin/bash

echo -n "Enter Name: "
read name
echo -n "Enter Accent: "
read accent
echo -n "Enter Accent 2: "
read accent2
echo -n "Enter Background: "
read bg
echo -n "Enter Text: "
read fg
echo -n "Enter Text Dark: "
read fgd

touch $HOME/.config/themes/$name
echo "$accent $accent2 $bg $fg $fgd" > $HOME/.config/themes/$name
