# espanso match file

# For a complete introduction, visit the official docs at: https://espanso.org/docs/

# You can use this file to define the base matches (aka snippets)
# that will be available in every application when using espanso.

# Matches are substitution rules: when you type the "trigger" string
# it gets replaced by the "replace" string.

global_vars:
  - name: clipboard
    type: clipboard


matches:
  - trigger: "rg14"
    replace: "shreyrg14@gmail.com"

  - trigger: "sp2"
    replace: "sp2117@cam.ac.uk"

  - trigger: "sout"
    replace: "System.out.println"

  - triggers: ["slef", "sefl"]
    replace: "self"
  - trigger: "improt"
    replace: "import"
  - triggers: ["bcz", "cuz"]
    replace: "because"
  - trigger: "probs"
    replace: "probably"
  - trigger: "idk"
    replace: "I don't know"

  - regex: 'shell:(?P<command>[a-zA-Z/ \-+$\(\)\\.0-9]+):'
    replace: "{{result}}"
    vars:
      - name: result
        type: shell
        params:
          cmd: "$ESPANSO_COMMAND"
          debug: true


        
  # And much more! For more information, visit the docs: https://espanso.org/docs/
